PREFIX obo:     <http://purl.obolibrary.org/obo/>
PREFIX time:    <http://www.w3.org/2006/time#>
PREFIX xsd:     <http://www.w3.org/2001/XMLSchema#>
PREFIX ti-o:    <https://w3id.org/zinl/ti-o#>


# Variabelen:
#   ?behandelingType – Klasse die de behandeling representeert
#   ?exclusie        – Klasse die de exclusie-disorder representeert
#   ?jaar            – het rapportagejaar als integer
#
# Pas de BIND blokken aan per indicator.

SELECT ?locatie (COUNT(DISTINCT ?behandeling) AS ?aantal)
WHERE {

    # --- Verslagperiode ---
    BIND(STRDT("2023-01-01", xsd:date) AS ?verslagPeriodeStart)
    BIND(STRDT("2024-01-01", xsd:date) AS ?verslagPeriodeEind)

    # # --- Behandeling (pas aan per indicator) ---
    BIND(ti-o:THP AS ?behandelingType)

    # # --- Exclusie (pas aan per indicator) ---
    BIND(ti-o:HipFracture AS ?exclusie)

    # --- Tijdsbinding: begindatum van de behandeling valt binnen verslagperiode ---
    ?behandeling time:hasTime/time:hasBeginning/time:inXSDDate ?datumBehandeling .
    FILTER ( ?datumBehandeling >= ?verslagPeriodeStart 
            && ?datumBehandeling < ?verslagPeriodeEind )

    # --- Patient met aandoening die wordt behandeld ---
    ?behandeling
        a ?behandelingType ;
        obo:RO_0000057 ?patient ;   # 'has participant' (heeft als deelnemer)
        obo:RO_0000057 ?disorder .

    ?patient
        a obo:NCBITAXON_9606 ;
        obo:BFO_00000137 ?disorder . # 'has continuant part at some time' (de disorder is van de deelnemende persoon)

    # --- Exclusie: behandeling heeft geen deelnemende disorder
    #     die aangeduid wordt door een exclusie klasse ---
    FILTER NOT EXISTS { ?disorder a ?exclusie . }

    # --- Zorglocatie ---
    ?behandeling obo:BFO_0000066 ?locatie . # 'occurs in' (vindt plaats in)
}
GROUP BY ?locatie
ORDER BY ?locatie